services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - pg-data-exove:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    environment:
      - PRODUCTS_URL=${PRODUCTS_URL}
      - POSTGRES_URL=${POSTGRES_URL}

networks:
  default:
    driver: bridge
volumes:
  pg-data-exove:
    driver: local
